<?php

/**
 * Do not edit this file manually, generated by the Yeoman Phalcon generator
 * Register application modules for the Karts project
 */
return [
	'frontend' => [
		'className' => '\Karts\Frontend\Module',
		'path'      => __DIR__ . '/../modules/frontend/Module.php',
	],

	'backend' => [
		'className' => '\Karts\Backend\Module',
		'path'      => __DIR__ . '/../modules/backend/Module.php',
	],

	'merchants' => [
		'className' => '\Karts\Merchants\Module',
		'path'      => __DIR__ . '/../modules/merchants/Module.php',
	],
];



